name: Build, Push, and Deploy Laravel App to EC2

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: selvakumaru/tradeschool
  TAG: latest

jobs:
  build-push-deploy:
    name: Build & Push Docker Image + Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          DOCKER_BUILDKIT=0 docker build --no-cache --build-arg ENV_FILE=.env -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || '22' }} ${{ secrets.EC2_HOST }} << EOF
            cd /var/www/trade-school/backend/tradeschool_deploy
            docker-compose pull
            docker-compose up -d
            docker-compose --profile setup up migrate
          EOF
